AddExt: 'aclnnAdd'
Bmm: 'aclnnBatchMatMul'
BatchMatMulExt: 'aclnnBatchMatMul'
Concat: 'aclnnCat'
SiLU: 'aclnnSilu'
Pow: 'aclnnPowTensorTensor'
Embedding: 'aclnnEmbedding'
EmbeddingDenseGrad: 'aclnnEmbeddingDenseGrad'
MatMulExt: 'aclnnMatmul'
MaskedFill: 'aclnnInplaceMaskedFillTensor'
GreaterEqual: 'aclnnGeTensor'
GeLU: 'aclnnGelu'
GeLUGrad: 'aclnnGeluBackward'
ReverseV2: 'aclnnFlip'
Less: 'aclnnLtTensor'
LessEqual: 'aclnnLeTensor'
SubExt: 'aclnnSub'
Sum: 'aclnnReduceSum'
SigmoidGrad: 'aclnnSigmoidBackward'
SiLUGrad: 'aclnnSiluBackward'
GatherDGradV2: 'aclnnScatterAdd'
GatherD: 'aclnnGather'
ReLU: 'aclnnRelu'
ReLUGrad: 'aclnnThresholdBackward'
LinSpaceExt: 'aclnnLinspace'
Tile: 'aclnnRepeat'
Transpose: 'aclnnPermute'
ArgMaxExt: 'aclnnArgMax'
Equal: 'aclnnEqTensor'
Greater: 'aclnnGtTensor'
ArgMaxWithValue: 'aclnnMaxDim'
ArgMinWithValue: 'aclnnMinDim'
ReduceAny: 'aclnnAny'
GroupNormGrad: 'aclnnGroupNormBackward'
NotEqual: 'aclnnNeTensor'
ClampScalar: 'aclnnClamp'
OneHotExt: 'aclnnOneHot'
Select: 'aclnnSWhere'
MaxPoolWithIndices: 'aclnnMaxPool2dWithIndices'
MaxpoolGradWithIndices: 'aclnnMaxPool2dWithIndicesBackward'
MaxPoolWithMask: 'aclnnMaxPool2dWithMask'
MaxPoolGradWithMask: 'aclnnMaxPool2dWithMaskBackward'
SoftplusExt: 'aclnnSoftplus'
SoftplusGradExt: 'aclnnSoftplusBackward'
